"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var rectangle_1 = require("./shapes/rectangle");
exports.Rectangle = rectangle_1.default;
var triangle_1 = require("./shapes/triangle");
exports.Triangle = triangle_1.default;
var ellipse_1 = require("./shapes/ellipse");
exports.Ellipse = ellipse_1.default;
var textbox_1 = require("./speciality/textbox");
exports.Textbox = textbox_1.default;
var image_1 = require("./speciality/image");
exports.Image = image_1.default;
